# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e189d3e1d6996ffcaf939ee08e61447a7d51ac9284831fb106bf87f694a820dc2609886cdd5bd05148b87cbd41e91bb0bc25d950f8936560bba1dea505de614a

test:
  secret_key_base: b08876c0d0dfd5503ce807b42c03d4eb6c4cebcfa58f6b986e19b4e0d605655b766e2ab715b6d6a30d9473193ae490057e3b770665d269a1a310025816b56e62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
